on:
  issue_comment:
    types: [created]
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: khan/pull-request-comment-trigger@master
        id: check
        with:
          trigger: '@roboneuro do this'
          reaction: rocket
        env:
          GITHUB_TOKEN: '${{ secrets.ACTIONS_WORKFLOW }}'
      - run: 'echo Found it!'
        if: steps.check.outputs.triggered == 'true'
